FROM ubuntu:16.04
RUN apt-get update
COPY apt-requirements.txt /root/apt-requirements.txt
RUN apt-get install --yes $(cat /root/apt-requirements.txt)
RUN curl 'https://bootstrap.pypa.io/pip/2.7/get-pip.py' | python
COPY dev-requirements.txt /root/dev-requirements.txt
RUN python -m pip install -r /root/dev-requirements.txt
RUN rm -f /root/dev-requirements.txt /root/apt-requirements.txt