FROM rockylinux:8
RUN dnf makecache --refresh
COPY rocky-requirements.txt /root/rpm-requirements.txt
RUN dnf install --assumeyes $(cat /root/rpm-requirements.txt)
RUN ln -sf $(which python2) /usr/bin/python
RUN curl 'https://bootstrap.pypa.io/pip/2.7/get-pip.py' | python
COPY dev-requirements.txt /root/dev-requirements.txt
RUN python -m pip install -r /root/dev-requirements.txt
RUN rm -f /root/dev-requirements.txt /root/rpm-requirements.txt